lang:
  default: ja
  e: en
redirect:
  "/index.html": "/"
  "/cal/cal.html": "/growings/"
  "/cal/cal_fun.html": "/growings/"
  "/cal/cal_coffee.html": "/growings/calanthe/info_coffeecup_calanthe"
  "/pone/pone.html": "/growings/"
  "/pone/pone_fun.html": "/growings/ponerorchis/"
  "/sai/sai_first.html": "/growings/calanthe/"
  "/sai/sai_kan.html": "/growings/calanthe/growings_tech_to_grow_calanthe_for_beginner"
  "/sai/sai_type.html": "/growings/calanthe/info_types_of_calanthe"
  "/sai/sai_jiebine.html": "/growings/calanthe/info_about_JIEBINE_calanthe_discolor"
  "/sai/sai_spring.html": "/growings/calanthe/growings_calanthe_on_season_01_spring"
  "/sai/sai_summer.html": "/growings/calanthe/growings_calanthe_on_season_02_summer"
  "/sai/sai_autumn.html": "/growings/calanthe/growings_calanthe_on_season_03_autumn"
  "/sai/sai_winter.html": "/growings/calanthe/growings_calanthe_on_season_04_winter"
  "/sai/sai_kabu.html": "/growings/calanthe/growings_repot_calanthe"
  "/sai/sai_zisei.html": "/growings/calanthe/info_lerning_calanthe_from_territory"
  "/sai/sai_fertilizer.html": "/growings/calanthe/growings_fertilizing_for_calanthe"
  "/sai/sai_cultivation.html": "/growings/calanthe/growings_calanthe_in_a_pot"
  "/sai/sai_garden.html": "/growings/calanthe/growings_calanthe_on_a_garden"
  "/sai/sai_byougai.html": "/growings/calanthe/growings_controlling_pests_of_calanthe"
  "/sai2/sai2_first.html": "/growings/ponerorchis/"
  "/sai2/sai2_pon.html": "/growings/ponerorchis/info_basics_of_ponerorchis"
  "/sai2/sai2_mmrr.html": "/growings/ponerorchis/growings_as_miniminiranran"
  "/sai2/sai2_kan.html": "/growings/ponerorchis/growings_tech_to_grow_ponerorchis_01_for_beginner"
  "/sai2/sai2_usai.html": "/growings/ponerorchis/pot_soil_water"
  "/sai2/sai2_zyou.html": "/growings/ponerorchis/growings_tech_to_grow_ponerorchis_02_for_advanced"
  "/sai2/sai2_u.html": "/growings/ponerorchis/info_types_of_ponerorchis"
  "/sai2/sai2_a.html": "/growings/ponerorchis/info_types_of_ponerorchis"
  "/sai2/sai2_k.html": "/growings/ponerorchis/info_types_of_ponerorchis"
  "/sai2/sai2_s.html": "/growings/ponerorchis/info_types_of_ponerorchis"
  "/sai2/sai2_h.html": "/growings/ponerorchis/info_types_of_ponerorchis"
  "/sai2/sai2_n.html": "/growings/ponerorchis/info_types_of_ponerorchis"
  "/sai2/sai2_ti.html": "/growings/ponerorchis/info_types_of_ponerorchis"
  "/sai2/sai2_ta.html": "/growings/ponerorchis/"
  "/sai2/sai2_zisei.html": "/growings/ponerorchis/info_lerning_ponerorchis_from_territory"
  "/sai2/sai2_mi.html": "/growings/ponerorchis/growings_watering_for_ponerorchis"
  "/sai2/sai2_mo.html": "/growings/ponerorchis/growings_overcome_the_intense_heat"
  "/sai2/sai2_miz.html": "/growings/ponerorchis/growings_ponerorchis_in_a_6cm_pot"
  "/sai2/sai2_ya.html": "/growings/ponerorchis/growings_ponerorchis_in_a_6cm_pot"
  "/sai2/sai2_kaika.html": "/growings/ponerorchis/growings_regulation_of_flowering_time"
  "/sai2/sai2_byougai.html": "/growings/ponerorchis/growings_controlling_pests_of_ponerorchis"
  "/sai3/": "/growings/recent_failure_and_provision"
  "/guide/guide.html": "/about_us/"
  "/guide/guide_dvd.html": "/about_us/"
  "/guide/guide_2012.html": "/about_us/"
  "/guide/guide_2011.html": "/about_us/"
  "/guide/guide_2010.html": "/about_us/"
  "/guide/guide_ranyuen.html": "/about_us/"
  "/guide/guide_access.html": "/about_us/direction"
  "/guide/guide_book.html": "/growings/calanthe/"
  "/guide/guide_wanted.html": "/about_us/"
  "/e": "/en/"
  "/e/": "/en/"
  "/e/cal/cal_lady.html": "/en/growings/calanthe/growings_tech_to_grow_calanthe_for_beginner"
  "/e/cal/cal_pro.html": "/en/growings/calanthe/growings_tech_to_grow_calanthe_for_beginner"
  "/e/cal/cal.html": "/en/growings/calanthe/growings_tech_to_grow_calanthe_for_beginner"
  "/e/cal/cal_mus.html": "/en/growings/calanthe/growings_tech_to_grow_calanthe_for_beginner"
  "/e/cal/cal_spring.html": "/en/growings/calanthe/growings_tech_to_grow_calanthe_for_beginner"
  "/e/cal/cal_fun.html": "/en/growings/calanthe/growings_tech_to_grow_calanthe_for_beginner"
  "/e/e/pone.html": "/en/growings/ponerorchis/growings_tech_to_grow_ponerorchis_01_for_beginner"
  "/e/e/index.html": "/en/"
  "/cal_bloom.html": "/growings/calanthe/"
  "/e/cal/cal_full.html": "/en/growings/calanthe/growings_tech_to_grow_calanthe_for_beginner"
  "/e/cal/cal_blo.html": "/en/growings/calanthe/growings_tech_to_grow_calanthe_for_beginner"
  "/e/cal/cal_oji.html": "/en/growings/calanthe/growings_tech_to_grow_calanthe_for_beginner"
  "/e/cal/cal_haru.html": "/en/growings/calanthe/growings_tech_to_grow_calanthe_for_beginner"
  "/pone.html": "/growings/ponerorchis/"
